# Templates and Variables
test_defaults: &test_defaults
  docker:
    - image: circleci/node:8.9.4
  steps:
    - checkout
    - restore_cache:
        keys:
        - js-dependencies-{{ checksum "package-lock.json" }}
        - js-dependencies-
    - run:
        name: Integration Test
        command: npm run test:automation:sauce -- --suite ${TEST_SUITE}
        no_output_timeout: 40m
    - store_test_results:
        path: reports/junit/wdio
    - store_artifacts:
        path: reports/junit/wdio

test_base_url: &test_base_url
  JOURNEY_TEST_BASE_URL: https://practical-roentgen-7d4de0.netlify.com

# Main Config
version: 2
jobs:
  install:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package-lock.json" }}
          - js-dependencies-
      - run: echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} >> .npmrc
      - run: npm install
      - run: git checkout .npmrc
      - save_cache:
          paths:
            - node_modules
          key: js-dependencies-{{ checksum "package-lock.json" }}

  unit_tests_and_linting:
    docker:
      - image: circleci/node:8.9.4
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package-lock.json" }}
          - js-dependencies-
      - run:
          name: Run eslint
          command: npm run eslint -- --format junit -o reports/junit/js-lint-results.xml
      - run:
          name: Run all Jest test suites
          command: npm run jest -- --ci --testResultsProcessor="jest-junit"
          environment:
            JEST_JUNIT_OUTPUT: reports/junit/js-jest-results.xml
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit

  build_for_tests:
    docker:
      - image: circleci/node:8.9.4
    environment:
      - NODE_ENV: "test"
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package-lock.json" }}
          - js-dependencies-
      - run:
          name: Copy journey test static files
          command: |
            mkdir -p /tmp
            cp -r ./test/journeys/server /tmp/dist-test
            cp -r ./node_modules/axe-core /tmp/dist-test/
      - run:
          name: Build Space Widget
          command: npm run build:package widget-space
          environment:
            BUILD_DIST_PATH: /tmp/dist-test/dist-space
      - run:
          name: Build Recents Widget
          command: npm run build:package widget-recents
          environment:
            BUILD_DIST_PATH: /tmp/dist-test/dist-recents
      - persist_to_workspace:
          root: /tmp
          paths:
            - dist-test

  deploy_for_testing:
    docker:
      - image: circleci/node:8.9.4
    environment:
      - SITE_ID: "cb5e410a-9679-4ef3-99dc-82b89143e494"
      - DEPLOY_PATH: "/tmp/workspace/dist-test"
    steps:
      - checkout
      - restore_cache:
          keys:
          - js-dependencies-{{ checksum "package-lock.json" }}
          - js-dependencies-
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Deploy testing payload to Netlify
          command: npx netlify deploy -s ${SITE_ID} -p ${DEPLOY_PATH} -t ${NETLIFY_TOKEN}

  firefox_mac_oneOnOne_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: firefox
      - TEST_SUITE: oneOnOne
    <<: *test_defaults

  firefox_mac_recents_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: firefox
      - TEST_SUITE: recents
    <<: *test_defaults

  firefox_mac_space_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: firefox
      - TEST_SUITE: space
    <<: *test_defaults

  firefox_mac_multiple_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: firefox
      - TEST_SUITE: multiple
    <<: *test_defaults

  chrome_mac_oneOnOne_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - TEST_SUITE: oneOnOne
    <<: *test_defaults

  chrome_mac_recents_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - TEST_SUITE: recents
    <<: *test_defaults

  chrome_mac_space_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - TEST_SUITE: space
    <<: *test_defaults

  chrome_mac_multiple_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - TEST_SUITE: multiple
    <<: *test_defaults

  chrome_win10_oneOnOne_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - PLATFORM: windows 10
      - TEST_SUITE: oneOnOne
    <<: *test_defaults

  chrome_win10_recents_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - PLATFORM: windows 10
      - TEST_SUITE: recents
    <<: *test_defaults

  chrome_win10_space_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - PLATFORM: windows 10
      - TEST_SUITE: space
    <<: *test_defaults

  chrome_win10_multiple_tests:
    environment:
      - <<: *test_base_url
      - BROWSER: chrome
      - PLATFORM: windows 10
      - TEST_SUITE: multiple
    <<: *test_defaults

workflows:
  version: 2
  run_all_tests:
    jobs:
      - install
      - build_for_tests:
          requires:
            - install
      - unit_tests_and_linting:
          requires:
            - install
      - deploy_for_testing:
          requires:
            - build_for_tests
      - firefox_mac_oneOnOne_tests:
          requires:
            - deploy_for_testing
      - firefox_mac_recents_tests:
          requires:
            - deploy_for_testing
      - firefox_mac_space_tests:
          requires:
            - deploy_for_testing
      - firefox_mac_multiple_tests:
          requires:
            - deploy_for_testing
      - chrome_mac_oneOnOne_tests:
          requires:
            - deploy_for_testing
      - chrome_mac_recents_tests:
          requires:
            - deploy_for_testing
      - chrome_mac_space_tests:
          requires:
            - deploy_for_testing
      - chrome_mac_multiple_tests:
          requires:
            - deploy_for_testing
      - chrome_win10_oneOnOne_tests:
          requires:
            - deploy_for_testing
      - chrome_win10_recents_tests:
          requires:
            - deploy_for_testing
      - chrome_win10_space_tests:
          requires:
            - deploy_for_testing
      - chrome_win10_multiple_tests:
          requires:
            - deploy_for_testing
